# This app.yaml is for deploying to instances of Cloud SQL running MySQL.
# See app-postgres.yaml for running Cloud SQL with PostgreSQL.

# [START gae_cloudsql_mysql_env]
# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php72

env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  CLOUDSQL_USER:root
  CLOUDSQL_PASSWORD:Nefer!123
  CLOUDSQL_DSN: "mysql:dbname=my_store;unix_socket=/cloudsql/lateral-imagery-273907:us-central1:pettybebe"
# [END gae_cloudsql_mysql_env]  